#!/usr/bin/expect -f
## ARGS 0->dpid 1->range 2->add or not 3->delete or not

# Copyright (C) 2013-2014, OpenMUL foundation 
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
#    the
#    License for the specific language governing permissions and limitations
#    under the License.


log_user 0
spawn telnet localhost 10000
expect ">"
send "enable\r"
log_user 1
expect "#"
send "show ha-state\r"
expect "#"
log_user 0
send "exit\r"
expect eof

